/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:bcbee66a-6eaf-4a01-ab09-0fe8d103484b",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_hwlCSIakV",
    "aws_user_pools_web_client_id": "1linutl8914hegrdj9dgbb2p2v",
    "oauth": {}
};


export default awsmobile;
